package publicTransport;

import events.Event;
import events.GoOnStop;
import events.Queue;

/**
 * Passenger are simulation actors, who at the beginning gets their number (as a name)
 * and home stop, which was generated by pseudo-random draw.
 * Later on they are given destination, which is also drawn. That is the stop on which
 * they are planning on getting.
 * starTime is needed to count time of actions performed by passengers ex. time of
 * waiting on the stop.
 */
public class Passenger {
    private final Stop homeStop;
    private final int number;
    private Stop destination;
    private int startTime;

    public Passenger(int number, Stop homeStop){
        this.number = number;
        this.homeStop = homeStop;
    }

    @Override
    public String toString() {
        return "Passenger " + number;
    }

    public void setDestination(Stop destination) {
        this.destination = destination;
    }

    public int getNumber() {
        return number;
    }

    public Stop getHomeStop() {
        return homeStop;
    }

    public Stop getDestination() {
        return destination;
    }

    public void setStartTime(int startTime) {
        this.startTime = startTime;
    }

    public int getStartTime() {
        return startTime;
    }

    public void goOnStop(Queue events, int time) {
        GoOnStop event = new GoOnStop(this);
        Event temp = new Event(event, time);
        events.put((temp));
        this.startTime = time;
    }
}
